p8105_hw3_jg5038
================
Julia Gray
2025-10-02

Problem 1

``` r
data("instacart")

instacart |> 
  janitor::clean_names()
```

    ## # A tibble: 1,384,617 × 15
    ##    order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##       <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ##  1        1      49302                 1         1  112108 train               4
    ##  2        1      11109                 2         1  112108 train               4
    ##  3        1      10246                 3         0  112108 train               4
    ##  4        1      49683                 4         0  112108 train               4
    ##  5        1      43633                 5         1  112108 train               4
    ##  6        1      13176                 6         0  112108 train               4
    ##  7        1      47209                 7         0  112108 train               4
    ##  8        1      22035                 8         1  112108 train               4
    ##  9       36      39612                 1         0   79431 train              23
    ## 10       36      19660                 2         1   79431 train              23
    ## # ℹ 1,384,607 more rows
    ## # ℹ 8 more variables: order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

This dataset contains order information from instacart. It is organized
by order and contains information about the products ordered, as well as
information about the customer (i.e. how long it’s been since they last
ordered). It contains 1384617 observations and includes columns for
order_id, product_id, add_to_cart_order, reordered, user_id, eval_set,
order_number, order_dow, order_hour_of_day, days_since_prior_order,
product_name, aisle_id, department_id, aisle, department. For example,
the first order in the dataset was made by 112108 at 10 o clock and we
can see they ordered c(“Bulgarian Yogurt”, “Organic 4% Milk Fat Whole
Milk Cottage Cheese”, “Organic Celery Hearts”, “Cucumber Kirby”,
“Lightly Smoked Sardines in Olive Oil”, “Bag of Organic Bananas”,
“Organic Hass Avocado”, “Organic Whole String Cheese”) (of which
c(“Bulgarian Yogurt”, “Organic 4% Milk Fat Whole Milk Cottage Cheese”,
“Lightly Smoked Sardines in Olive Oil”, “Organic Whole String Cheese”)
were reordered).

There are 134 unique aisles. Here is a table of the aisles most ordered
from (just showing the top 10):

``` r
instacart_aisle_sum_df = instacart |> 
  group_by(aisle) |> 
  summarize(
    n = n()
  ) |> 
  arrange(desc(n)) 

instacart_aisle_sum_df |> 
  head(10) |> 
  knitr::kable()
```

| aisle                         |      n |
|:------------------------------|-------:|
| fresh vegetables              | 150609 |
| fresh fruits                  | 150473 |
| packaged vegetables fruits    |  78493 |
| yogurt                        |  55240 |
| packaged cheese               |  41699 |
| water seltzer sparkling water |  36617 |
| milk                          |  32644 |
| chips pretzels                |  31269 |
| soy lactosefree               |  26240 |
| bread                         |  23635 |

Now let’s plot aisles with more than 10,000 items ordered from them:

``` r
#UPDATE labels and size to render correctly
instacart_aisle_sum_df |> 
  filter(n >= 10000) |> 
  ggplot(aes(x=reorder(aisle, n), y=n)) +
  geom_bar(stat="identity") +
  coord_flip()
```

<img src="p8105_hw3_jg5038_files/figure-gfm/unnamed-chunk-3-1.png" width="90%" />

In order to find the most popular items for each aisle let’s group by:

``` r
instacart_aisle_item_df = instacart |> 
  group_by(aisle) |> 
  count(product_name) |> 
  mutate(
    item_aisle_rank = min_rank(desc(n))
    ) |> 
  filter(aisle %in% c('baking ingredients', 'dog food care', 'packaged vegetables fruits'), item_aisle_rank <= 3) |> 
  arrange(aisle, item_aisle_rank)

knitr::kable(instacart_aisle_item_df)
```

| aisle                      | product_name                                  |    n | item_aisle_rank |
|:---------------------------|:----------------------------------------------|-----:|----------------:|
| baking ingredients         | Light Brown Sugar                             |  499 |               1 |
| baking ingredients         | Pure Baking Soda                              |  387 |               2 |
| baking ingredients         | Cane Sugar                                    |  336 |               3 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |   30 |               1 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |   28 |               2 |
| dog food care              | Small Dog Biscuits                            |   26 |               3 |
| packaged vegetables fruits | Organic Baby Spinach                          | 9784 |               1 |
| packaged vegetables fruits | Organic Raspberries                           | 5546 |               2 |
| packaged vegetables fruits | Organic Blueberries                           | 4966 |               3 |
